GTEST_DIR = contrib/googletest/googletest
GTEST_SRCS = $(GTEST_DIR)/src/*.cc
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
				$(GTEST_DIR)/include/gtest/internal/*.h

CPPFLAGS += -isystem $(GTEST_DIR)/include
CXXFLAGS += -g -Wall -Wextra --std=c++11

gtest-all.o : $(GTEST_SRCS)
	$(CXX) $(CPPFLAGS) -I $(GTEST_DIR) $(CXXFLAGS) -c $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS)
	$(CXX) $(CPPFLAGS) -I $(GTEST_DIR) $(CXXFLAGS) -c $(GTEST_DIR)/src/gtest_main.cc

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

dictionary.o : dictionary.cpp dictionary.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c dictionary.cpp

dictionary_ut.o : dictionary_ut.cpp dictionary.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c dictionary_ut.cpp

word_search.o : word_search.cpp word_search.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c word_search.cpp

word_search_ut.o : word_search_ut.cpp word_search.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c word_search_ut.cpp

unittest : dictionary.o dictionary_ut.o word_search.o word_search_ut.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $^ -o $@

clean :
	rm -rf *.o
	rm -rf *.a
